---
- name: Converge
  hosts: all
  tasks:
    - name: install system deps
      apt:
        name:
          - cron
          - python-apt
          - python-pip
          - python-setuptools
          - python3-pip
          - python3-setuptools
          - virtualenv
        state: latest
    - name: "Include scriabin"
      include_role:
        name: "scriabin"
