---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible
  - name: ubuntu1604
    image: geerlingguy/docker-ubuntu1604-ansible
provisioner:
  name: ansible
verifier:
  name: ansible
